name: CI-CD

# Dispara o workflow em push na branch "main", merge na branch "main" ou manualmente
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Job CI: Compilação e testes do projeto
  CI:
    runs-on: ubuntu-latest

    # Define a estratégia de matriz para o job
    strategy:
      matrix:
        # Define a versão do Node.js a ser utilizada
        node-version: [18.x]

    steps:
      # Passo 1: Faz o checkout do código-fonte do repositório
      - name: Checkout do código-fonte do repositório
        uses: actions/checkout@v4

      # Passo 2: Configuração do ambiente Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # Usa cache npm para acelerar a instalação de dependências
          cache: 'npm'

      # Passo 3: Instalação das dependências do projeto
      - name: Instalar dependências do projeto
        run: npm install

      # Passo 4: Instalação do Angular CLI globalmente
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # Passo 5: Construção do projeto Angular usando a configuração de produção
      - name: Construir o projeto Angular
        run: ng build --configuration production

      # Passo 6: Execução de testes unitários
      - name: Executar testes unitários
        run: ng test

  # Job zap_scan: Análise de segurança ZAP Scan
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan da aplicação web
    steps:
      # Passo 1: Faz o checkout do código-fonte do repositório
      - name: Checkout do código-fonte do repositório
        uses: actions/checkout@v4
        with:
          ref: main

      # Passo 2: Executa a análise de segurança ZAP Scan
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://www.boratrocar.net/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          allow_issue_writing: false
          artifact_name: 'zap_scan_report'

  # Job CD: Implantação contínua
  CD:
    runs-on: ubuntu-latest
    needs: [CI]

    steps:
      # Passo 1: Faz o checkout do código-fonte do repositório
      - name: Checkout do código-fonte do repositório
        uses: actions/checkout@v4
